### ISSUE TITLE
abuild -r is broken

### ISSUE THREAD

**Issue by linuxneverdies** [Artox/alpine-systemd#1]
Yesterday the build worked, but today there are checksum errors in the systemd patch files.
After updating the checksums with "abuild checksum" I got the following error:
>>> libsystemd: https://git.openembedded.org/openembedded-core/plain/meta/recipes-core/systemd/systemd/0006-Include-netinet-if_ether.h.patch
patching file src/basic/linux/in6.h
patching file src/libsystemd-network/sd-dhcp6-client.c
patching file src/libsystemd/sd-netlink/netlink-types.c
patching file src/machine/machine-dbus.c
patching file src/network/netdev/bond.c
patching file src/network/netdev/bridge.c
patching file src/network/netdev/macsec.c
patching file src/network/netdev/netdev-gperf.gperf
patching file src/network/netdev/netdev.c
patching file src/network/networkd-bridge-vlan.c
patching file src/network/networkd-dhcp-common.c
patching file src/network/networkd-dhcp-server.c
patching file src/network/networkd-dhcp4.c
patching file src/network/networkd-dhcp6.c
patching file src/network/networkd-link.c
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file src/network/networkd-link.c.rej
patching file src/network/networkd-network.c
patching file src/network/networkd-route.c
patching file src/network/networkd-setlink.c
patching file src/network/test-network-tables.c
patching file src/shared/ethtool-util.c
patching file src/shared/ethtool-util.h
patching file src/udev/net/link-config.c
patching file src/udev/udev-builtin-net_setup_link.c
>>> ERROR: libsystemd: prepare failed

**Comment by Artox** [comment]
Hi! I think this is because openembedded have updated their patches since I originally pulled them.
I have updated the URLs to always download the same version of those patches, that should fix the problem you are seeing.

Feel free to let me know if it doesn't.
